<template>
<div class="container">
  <div class="body mb-5 mt-5">
    <!-- Page Heading/Breadcrumbs -->
    <h1 class=" mb-3 text-center">About</h1>
    <hr />
    <div class="info">
      <div class="card mt-5 border-0">
        <div class="card-body">
          <h2 class="card-title">About IReN</h2>
          <p class="card-text">
            IReN is a web application developed to facilitate the creation and access of case studies regarding the
            multi-faceted infrastructure damages of natural disasters in Puerto Rico.
            The web application allows for the creation, searching, and editing of case studies and was developed by
            students from the University of Puerto Rico to help the RISE-UP initiative document, collaborate, and share information
            that will help create more resilient future infrastructure in Puerto Rico.
          </p>
          <h2 class="card-title">About RISE-UP</h2>
          <p class="card-text">
            The academic preparation of infrastructure related disciplines usually takes place in isolated professional domains,
            rarely tackling problems in an interdisciplinary manner and/or learn from the systematic research of previous experiences.
            In order to address this issue, the Resilient Infrastructure and Sustainability Education – Undergraduate Program (RISE-UP)
            will provide the intellectual and practical academic space to generate case study research and turn them into hands-on solutions
            for real problems/projects, starting with the ones generated by the impact of Hurricanes Irma and Maria.
            The timely collection of evidence of the infrastructure damages caused by the 2017 hurricanes in PR will facilitate
            the development of evidence-based solutions in the curriculum.
          </p>
          <hr />
          <h2 class="card-title text-center">Contact Information</h2>
          <p class="card-text text-center text-break">
            UPRM – PR-108, Mayagüez, 00682
            <br/>
            UPRP – Avenida Santiago de los Caballeros, Ponce, 00734
            <br/>
            UPRRP – Av. Dr. José N. Gándara, San Juan, 00931
            <br/>
            Contact e-mail: riseup@upr.edu
            <br/>
            RISE-UP Website:
            <a href="http://riseup.upr.edu">http://riseup.upr.edu</a>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
</template>

<script>
export default {};
</script>

<style lang="scss" scoped>
.card .card-body {
  padding-left: 20px;
  padding-right: 20px;
}
</style>
